### PR TITLE
Compile for visionOS

### PR DESCRIPTION
**Pull request by Hengyu**
- Make it compile for visionOS
- Not tested UI on visionOS

### CODE REVIEW

**Comment by Hengyu** [comment]
@russell-archer would you mind take a look, thanks!

**Comment by russell-archer** [comment]
Sorry for the delay in responding. Have been unwell with heart problems. On the mend now and will take a look at your PR as soon as I can!

**Comment by Hengyu** [comment]
@russell-archer sorry for that, wish you all the best and get better shortly

**Comment by russell-archer** [comment]
I've merged your PR. Thanks very much for your hard work in adding support for visionOS (sorry it took me so long to merge it!).

**Pull request merged**
